### ISSUE TITLE
atlas/cblas.h missing

### ISSUE THREAD

**Issue by hakank** [friguzzi/matrix#2]
Preamble:
I installed cplint via swipl's `pack_install(cplint)`, but got problem running programs using the mcintyre package, e.g. `gaussian_mixture.pl`. This problem was caused that the matrix package - installed via `pack_install(matrix)` - was not properly installed since atlas/cblas.h is not on my system (Linux Ubuntu 18.04 LTS).

The problem in this matrix package was fixed on my machine by replacing the following line (line 48) from `prolog/matrix.pl`:

   `:- c_import("#include <atlas/cblas.h>",`

to

  `:- c_import("#include <cblas.h>",`
 
(I did noticed the warning in this Git repo: "Work in progress, do not use for now.", but I have no choice since I want to use cplint. It seems to be really interesting.)

**Comment by malbertife** [comment]
Thanks for the accurate report and sorry for the inconvenience.
I rolled back to the previous stable version of this library.
Please uninstall and reinstall the `matrix` and `cplint` packages.

**Comment by hakank** [comment]
Have removed and reinstalled both packages. It works without any problem now.

Thanks.
